version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
    steps:
      - checkout
      - run:
          name: Run Bundler
          command: "bundle install"
      - run:
          name: Install Rspec
          command: "rpec"
      - run:
          name: Run tests
          command: "rpec"
