version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
    steps:
      - checkout
      - prepare-gems:
          name: Run Bundler
          command: "bundle install"
      - is-rails-there:
          name: Check Rails Version
          command: "rails -v"
      - go-server:
          name: Run Rails Server
          command: "rails s"
